# .gitlab-ci.yml
image: ruby:3.3

stages:
  - cleanup
  - deploy

pages:
  stage: deploy
  script:
    - gem install bundler
    - gem install jekyll
    - bundle install
    - bundle update
    - bundle exec jekyll build
    - mv _site public
    - gem cleanup
    - export GEM_PATH=$(gem env gemdir)
    - rm -rf $GEM_PATH
  artifacts:
    paths:
      - public
  only:
    - main
  retry: 2
