# .gitlab-ci.yml

image: ruby:3.3

pages:
  stage: deploy
  script:
    - gem install bundler
    - gem install jekyll
    - jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main
