# .gitlab-ci.yml
image: ruby:3.3

stages:
  - deploy
  - cleanup

pages:
  stage: deploy
  script:
    - gem install bundler
    - gem install jekyll
    - bundle install
    - bundle update
    - bundle exec jekyll build
    - mv _site public
    - gem cleanup
    - gem env gemdir
    - export GEM_PATH=$(gem env gemdir)
    - rm -rf $GEM_PATH
  artifacts:
    paths:
      - public
  only:
    - main
  
cleanup:
  stage: cleanup
  script:
    - gem env gemdir
    - export GEM_PATH=$(gem env gemdir)
    - rm -rf $GEM_PATH
  only:
    - main

