# .gitlab-ci.yml

image: ruby:2.7

pages:
  stage: deploy
  script:
    - gem install bundler
    - gem install jekyll
    - bundle install
    - bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --destination "_site"
  artifacts:
    paths:
      - public
  only:
    - main
