# .gitlab-ci.yml

image: ruby:3.3

pages:
  stage: deploy
  script:
    - gem install bundler
    - gem install jekyll
    - bundle install
    - bundle update
    - bundle exec jekyll build
    - mv _site public
    - docker system prune -a
    - docker volume prune
    - gem cleanup
  artifacts:
    paths:
      - public
  only:
    - main
  retry: 2
