# .gitlab-ci.yml
image: ruby:3.3

stages:
  - cleanup
  - deploy

cleanup:
  stage: cleanup
  script:
    - docker system prune -a -f
    - docker volume prune -f
  only:
    - main

pages:
  stage: deploy
  script:
    - gem install bundler
    - gem install jekyll
    - bundle install
    - bundle update
    - bundle exec jekyll build
    - mv _site public
    - docker system prune -a -f
    - docker volume prune -f
    - gem cleanup
  artifacts:
    paths:
      - public
  only:
    - main
  retry: 2
