# .gitlab-ci.yml

image: ruby:3.3

pages:
  stage: deploy
  script:
    - gem install bundler
    - gem install jekyll
    - bundle install
    - bundle exec jekyll build --trace
  artifacts:
    paths:
      - public
  only:
    - main
