name: Auto Create Merge Request

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Deploy Jekyll site to Pages
    types:
      - completed
    
  
jobs:
  Checkout_Code:
    runs-on: ubuntu-latest
    outputs:
      repo_synced: ${{ steps.check_git_status.outputs.repo_synced }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GH_TOKEN }}
            fetch-depth: 0

      - name: Set up Git Configurations
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Pull the latest change
        run: |
          git fetch origin main
          git fetch origin develop
          git checkout develop
          git merge -X theirs --allow-unrelated-histories --no-ff origin/main
          git push origin develop

      - name: Check Git Status
        id: check_git_status
        run: |
          git diff --exit-code
          echo "repo_synced=true" >> $GITHUB_OUTPUT
        continue-on-error: true

  Create_Pull_Request:
    runs-on: ubuntu-latest
    needs: Checkout_Code
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GH_TOKEN }}
            fetch-depth: 0
      - name: Checkout "develop" branch
        if: needs.Checkout_Code.outputs['repo_synced'] == 'true'
        run: |
          git checkout develop

      - name: Create pull request
        if: needs.Checkout_Code.outputs.repo_synced == 'true'
        uses: peter-evans/create-pull-request@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Merge develop into main"
          title: "Merge develop into main"
          body: "This is an auto-generated pull request to merge develop into main."
          branch: main
          base: develop
          labels: auto-merge
          assignees: github-actions[bot]
          reviewers: Lucas04-nhr
          draft: false
      
      - name: Set up Git Configurations
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push to GitHub
        run: |
          git fetch origin
          git checkout main
          git push
