name: Sync GitHub to GitLab

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    
  Checkout_GitHub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GH_TOKEN }}

  Push_to_GitLab:
    needs: Checkout_GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GH_TOKEN }}

      - name: Set up Git
        env:
            GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
            git config user.name "Lucas04"
            git config user.email "lucas04@foxmail.com"
            git config --global user.token $GITLAB_TOKEN

      - name: Push to GitLab
        env:
            GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
            git config pull.rebase false
            git remote add gitlab https://gitlab.igem.org/2024/hust-china.git
            git remote set-url gitlab https://Lucas04:vYestP-_1m6UCPwkgq6C@gitlab.igem.org/2024/hust-china.git
            git fetch --unshallow
            git merge -X ours --no-ff gitlab/main
            git commit -m "Sync GitHub to GitLab"
            git push gitlab main
        