name: Sync GitHub to GitLab

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    
  Checkout_GitHub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GH_TOKEN }}

  Push_to_GitLab:
    needs: Checkout_GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GH_TOKEN }}

      - name: Set up Git
        env:
            GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
            git config user.name "Lucas04"
            git config user.email "lucas04@foxmail.com"
            git config --global credential.helper "store --file=.git/credentials"
            echo "https://gitlab.igem.org username:${{ secrets.GITLAB_TOKEN }}" > ~/.git/credentials

      - name: Push to GitLab
        env:
            GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
            GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
            git remote add gitlab $GITLAB_REPO
            git push gitlab main
        