name: Sync GitLab to GitHub

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Pull_from_GitLab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Pull from GitLab
        env:
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
        
          git config --global credential.helper "store --file=.git/credentials"
          mkdir -p ${{ github.workspace }}/gitlab-repo
          git clone $GITLAB_REPO ${{ github.workspace }}/gitlab-repo
          git fetch origin
          git checkout main

  Push_to_GitHub:
    needs: Pull_from_GitLab
    runs-on: ubuntu-latest

    steps:
      - name: Sync to GitHub
        run: |

            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "GitHub Actions"
            git remote add github-origin ${{ github.repository }}
            git push github-origin main
