name: Sync GitHub to GitLab

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    
  Push_to_GitLab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GH_TOKEN }}

      - name: Set up Git
        env:
            GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
            git config user.name "Lucas04"
            git config user.email "lucas04@foxmail.com"
            git config --global user.token $GITLAB_TOKEN

      - name: Set up GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          # Configure GPG to use loopback mode for pinentry
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          gpg --batch --import ./gpg_key
          # Restart gpg-agent to apply the new configuration
          gpg-connect-agent reloadagent /bye
          # Import the GPG key
          echo -n "$GPG_PRIVATE_KEY" > gpg_key_base64
          echo "Encoded key length: $(wc -c <gpg_key_base64)"
          base64 -d gpg_key_base64 > gpg_key
          gpg --batch --yes --import ./gpg_key
          rm gpg_key gpg_key_base64
          git config --global gpg.program gpg
          git config --global gpg.sign true
          git config --global user.signingkey 5F155F58DE778A7B
        shell: bash
        
      - name: Push to GitLab
        env:
            GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
            git config pull.rebase false
            git remote add gitlab https://gitlab.igem.org/2024/hust-china.git
            git remote set-url gitlab https://Lucas04:vYestP-_1m6UCPwkgq6C@gitlab.igem.org/2024/hust-china.git
            # git fetch --unshallow gitlab main
            git merge -X ours --no-ff  --allow-unrelated-histories gitlab/main
            git push gitlab main

        