name: Sync GitLab to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  Pull_from_GitLab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GH_TOKEN }}

      - name: Set up GitLab
        run: |
          git config user.name "Lucas04"
          git config user.email "lucas04@foxmail.com"

      - name: Pull from GitLab
        env:
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab $GITLAB_REPO
          git fetch gitlab
          git merge -X theirs --allow-unrelated-histories --no-ff gitlab/main

  Push_to_GitHub:
    needs: Pull_from_GitLab
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config user.name "Lucas04-nhr"
          git config user.email "lucas04@foxmail.com"

      - name: Set Git Configurations
        run: |
          git config pull.rebase false

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin main
